import type { Metadata } from "next";
import Navbar from "@/components/layout/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-900 p-2 px-6 text-gray-400">
          <Navbar />
        </div>
        <div className="flex-grow font-light">{children}</div>
        <div className="bg-gray-800 p-3"></div>
      </body>
    </html>
  );
}
