import type { Metadata } from "next";
import Script from "next/script";
import Navbar from "@/components/layout/Navbar";
import Providers from "./providers";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trivialize App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="en">
      <Script src="https://kit.fontawesome.com/425025cd1d.js" />
      <body className={inter.className}>
        <div className="h-screen flex flex-col">
          <div className="bg-gray-900 p-2 px-6 text-gray-400 flex-shrink">
            <Navbar />
          </div>
          <div className="font-light flex flex-col flex-grow">
            <Providers>{children}</Providers>
          </div>
          <div className="bg-gray-800 p-3 flex-shrink text-gray-100">
            Footer
          </div>
        </div>
      </body>
    </html>
  );
}
